export enum SessionActionsType {
    CREATE_SESSION = 'CREATE_SESSION',
    CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS',
    CREATE_SESSION_FAILURE = 'CREATE_SESSION_FAILURE',
    CLOSING_SESSION = 'CLOSING_SESSION',
    CLOSED_SESSION = 'CLOSED_SESSION'
}