export enum OperationActionsType {
    PROC_GET_OPERATIONS = 'PROC_GET_OPERATIONS',
    SUCC_GET_OPERATIONS = 'SUCC_GET_OPERATIONS',
    FAILED_GET_OPERATIONS = 'FAILED_GET_OPERATIONS',

    PROC_GET_OPERATIONS_BY_USER = 'PROC_GET_OPERATIONS_BY_USER',
    SUCC_GET_OPERATIONS_BY_USER = 'SUCC_GET_OPERATIONS_BY_USER',
    FAILED_GET_OPERATIONS_BY_USER = 'FAILED_GET_OPERATIONS_BY_USER',
}