export enum ProfileActionsType {
    PROC_GET_PROFILE = 'PROC_GET_CURRENT_GAMER',
    SUCC_GET_PROFILE = 'SUCC_GET_CURRENT_GAMER',
    FAILED_GET_PROFILE = 'FAILED_GET_CURRENT_GAMER',

    PROC_GET_TAX = 'PROC_GET_CURRENT_TAX',
    SUCC_GET_TAX = 'SUCC_GET_CURRENT_TAX',
    FAILED_GET_TAX = 'FAILED_GET_CURRENT_TAX',

    PROC_GET_CHARACTERS = 'PROC_GET_CURRENT_CHARACTERS',
    SUCC_GET_CHARACTERS = 'SUCC_GET_CURRENT_CHARACTERS',
    FAILED_GET_CHARACTERS = 'FAILED_GET_CURRENT_CHARACTERS',

    PROC_SET_MAIN = 'PROC_CURRENT_SET_MAIN',
    SUCC_SET_MAIN = 'SUCC_CURRENT_SET_MAIN',
    FAILED_SET_MAIN = 'FAILED_CURRENT_SET_MAIN',

    PROC_DELETE_CHAR = "PROC_CURRENT_DELETE_CHAR",
    SUCC_DELETE_CHAR = "SUCC_CURRENT_DELETE_CHAR",
    FAILED_DELETE_CHAR = "FAILED_CURRENT_DELETE_CHAR",

    PROC_ADD_NEW_CHAR = "PROC_CURRENT_ADD_NEW_CHAR",
    SUCC_ADD_NEW_CHAR = "SUCC_CURRENT_ADD_NEW_CHAR",
    FAILED_ADD_NEW_CHAR = "FAILED_CURRENT_ADD_NEW_CHAR"
}