export enum GamerActionsType {
    PROC_GET_CURRENT_GAMER = 'PROC_GET_CURRENT_GAMER',
    SUCC_GET_CURRENT_GAMER = 'SUCC_GET_CURRENT_GAMER',
    FAILED_GET_CURRENT_GAMER = 'FAILED_GET_CURRENT_GAMER',
}