export enum GamerActionsType {
    PROC_GET_CURRENT_GAMER = 'PROC_GET_CURRENT_GAMER',
    SUCC_GET_CURRENT_GAMER = 'SUCC_GET_CURRENT_GAMER',
    FAILED_GET_CURRENT_GAMER = 'FAILED_GET_CURRENT_GAMER',

    PROC_GET_GUILD_GAMERS = 'PROC_GET_GUILD_GAMERS',
    SUCC_GET_GUILD_GAMERS = 'SUCC_GET_GUILD_GAMERS',
    FAILED_GET_GUILD_GAMERS = 'FAILED_GET_GUILD_GAMERS',

    PROC_SET_GAMER_STATUS = 'PROC_SET_GAMER_STATUS',
    SUCC_SET_GAMER_STATUS = 'SUCC_SET_GAMER_STATUS',
    FAILED_SET_GAMER_STATUS = 'FAILED_SET_GAMER_STATUS',

    PROC_SET_GAMER_RANK = 'PROC_SET_GAMER_RANK',
    SUCC_SET_GAMER_RANK = 'SUCC_SET_GAMER_RANK',
    FAILED_SET_GAMER_RANK = 'FAILED_SET_GAMER_RANK',

    PROC_ADD_NEW_CHARS = 'PROC_ADD_NEW_CHARS',
    SUCC_ADD_NEW_CHARS = 'SUCC_ADD_NEW_CHARS',
    FAILED_ADD_NEW_CHARS = 'FAILED_ADD_NEW_CHARS',

    PROC_DELETE_CHARS = 'PROC_DELETE_CHARS',
    SUCC_DELETE_CHARS = 'SUCC_DELETE_CHARS',
    FAILED_DELETE_CHARS = 'FAILED_DELETE_CHARS',

    PROC_ADD_GAMER_LOAN = 'PROC_ADD_GAMER_LOAN',
    SUCC_ADD_GAMER_LOAN = 'SUCC_ADD_GAMER_LOAN',
    FAILED_ADD_GAMER_LOAN = 'FAILED_ADD_GAMER_LOAN',

    PROC_ADD_GAMER_PENALTY = 'PROC_ADD_GAMER_PENALTY',
    SUCC_ADD_GAMER_PENALTY = 'SUCC_ADD_GAMER_PENALTY',
    FAILED_ADD_GAMER_PENALTY = 'FAILED_ADD_GAMER_PENALTY',

    PROC_CANCEL_GAMER_LOAN = 'PROC_CANCEL_GAMER_LOAN',
    SUCC_CANCEL_GAMER_LOAN = 'SUCC_CANCEL_GAMER_LOAN',
    FAILED_CANCEL_GAMER_LOAN = 'FAILED_CANCEL_GAMER_LOAN',

    PROC_CANCEL_GAMER_PENALTY = 'PROC_CANCEL_GAMER_PENALTY',
    SUCC_CANCEL_GAMER_PENALTY = 'SUCC_CANCEL_GAMER_PENALTY',
    FAILED_CANCEL_GAMER_PENALTY = 'FAILED_CANCEL_GAMER_PENALTY',
}