export enum OperationActionsType {
    PROC_GET_OPERATIONS = 'PROC_GET_OPERATIONS',
    SUCC_GET_OPERATIONS = 'SUCC_GET_OPERATIONS',
    FAILED_GET_OPERATIONS = 'FAILED_GET_OPERATIONS',

    PROC_CREATE_OPERATION = 'PROC_CREATE_OPERATION',
    SUCC_CREATE_OPERATION = 'SUCC_CREATE_OPERATION',
    FAILED_CREATE_OPERATION = 'FAILED_CREATE_OPERATION',
}