export enum GuildActionsType {
    PROC_GET_GUILD = 'PROC_GET_GUILD',
    SUCC_GET_GUILD = 'SUCC_GET_GUILD',
    FAILED_GET_GUILD = 'FAILED_GET_GUILD',
    
    PROC_GET_BALANCE_REPORT = 'PROC_GET_BALANCE_REPORT',
    SUCC_GET_BALANCE_REPORT = 'SUCC_GET_BALANCE_REPORT',
    FAILED_GET_BALANCE_REPORT = 'FAILED_GET_BALANCE_REPORT',
}